name: Type-check and Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  OS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Bootstrap packages
        run: yarn bootstrap

      - name: Type checks
        run: yarn type-check

      - name: Lint
        run: yarn lint
